import math
import straight_path_params

AXLE_LENGTH                  = 0.1
WHEEL_LENGTH_FROM_CENTER     = AXLE_LENGTH / 2
WHEEL_DIAMETER               = 0.065
WHEEL_RADIUS                 = WHEEL_DIAMETER / 2
WHEEL_CIRCUMFERANCE          = WHEEL_DIAMETER * math.pi

ROBOT_CENTER_RADIUS          = straight_path_params.PATH_RADIUS
ROBOT_RIGHT_WHEEL_RADIUS     = ROBOT_CENTER_RADIUS + WHEEL_LENGTH_FROM_CENTER
ROBOT_LEFT_WHEEL_RADIUS      = ROBOT_CENTER_RADIUS - WHEEL_LENGTH_FROM_CENTER
VELOCITY_RATIO_RIGHT         = ROBOT_RIGHT_WHEEL_RADIUS / ROBOT_CENTER_RADIUS
VELOCITY_RATIO_LEFT          = ROBOT_LEFT_WHEEL_RADIUS / ROBOT_CENTER_RADIUS

LEFT_TURN_90_DEGREES_LENGTH  = (AXLE_LENGTH * math.pi) / 4
RIGHT_TURN_90_DEGREES_LENGTH = -1 * (AXLE_LENGTH * math.pi) / 4
LEFT_TURN_WHEEL_ROTATIONS    = LEFT_TURN_90_DEGREES_LENGTH / WHEEL_CIRCUMFERANCE
RIGHT_TURN_WHEEL_ROTATIONS   = RIGHT_TURN_90_DEGREES_LENGTH / WHEEL_CIRCUMFERANCE